---
  batch_size: 64
  num_epochs: 30
  mxm_train_file: './data_files/mxm_dataset_train.txt'
  mxm_test_file: './data_files/mxm_dataset_test.txt'
  lastfm_db: './data_files/lastfm_similars.db'
  num_workers: 2
  