---
  batch_size: 16
  learning_rate: 0.002
  momentum: 0.9
  num_epochs: 10
  num_workers: 4
  num_examples: 500000
  keep_words: 128
  hidden_size_0: 128
  hidden_size_1: 128
  mxm_db: './data_files/mxm_lastfm.db'
