---
  batch_size: 16
  learning_rate: 0.001
  momentum: 0.9
  num_epochs: 10
  num_workers: 4
  num_examples: 1000000
  keep_words: 1024
  hidden_size_0: 1024
  hidden_size_1: 128
  mxm_db: './data_files/mxm_lastfm.db'
