---
  lyrics_db_path: './data_files/mxm_lyrics_cleaned.db'
  mxm_db_path: './data_files/mxm_dataset.db'
  lastfm_db_path: './data_files/mxm_lastfm.db'
  batch_size: 128
  emb_size: 20
  hidden_size: 10
  dropout: 0.9
  num_fc: 2
  combo_unit: 'ADD'
  num_epochs: 5
  num_workers: 0
  model_name: 'lstm_model_fc2_add_cleaned'